config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'conspects/tags/:tag', to: 'conspects#index', as: :tag
  root 'conspects#index'
  resources :photos
  resources :conspects do
    get :autocomplete_tag_name, :on => :collection
    resources :comments do
      member do
        put 'like', to: 'comments#upvote'
      end
    end
  end

  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :conspect
  validates :content, presence: true, length: { maximum: 250 }

  acts_as_votable

  searchable do
    text :content
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @conspect = Conspect.find(params[:conspect_id])
    @comment = @conspect.comments.create(params[:comment].permit(:user_name, :content))
    @comment.user_name = current_user.email
    @comment.save
    redirect_to conspect_path(@conspect)
  end

  def upvote
    @conspect = Conspect.find(params[:id])
    @comment = Comment.find(params[:conspect_id])
    if current_user.voted_up_for? @comment
      @comment.unliked_by current_user
    else
      @comment.liked_by current_user
    end
    redirect_to @conspect
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @conspect.comments.each do |comment| %>
  <p><%= comment.user_name %></p>
  <p><%= comment.content %></p>
  <%= link_to like_conspect_comment_path(comment), method: :put do %>
    <button class="btn btn-primary">Like</button>
    <span>Likes: <%= comment.get_likes.size %></span>
  <% end %>
  <hr>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@conspect, @conspect.comments.build]) do |form| %>

  <form>
    <div class="form-group d-flex justify-content-center mb-2">
      <%= form.text_area :content, class: "form-control", rows: "3" %>
    </div>
    <div class="d-flex justify-content-center mb-2">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </form>

<% end %>