config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'conspects/tags/:tag', to: 'conspects#index', as: :tag
  root 'conspects#index'
  resources :photos
  resources :conspects do
    get :autocomplete_tag_name, :on => :collection
    resources :comments do
      member do
        put 'like', to: 'comments#upvote'
      end
    end
  end

  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conspect.rb
class Conspect < ApplicationRecord
  belongs_to :user, class_name: User.name, foreign_key: :user_id
  has_many :comments, dependent: :destroy

  validates :title,presence: true, length: { maximum: 50}
  validates :description,presence: true, length: { maximum: 80}
  validates :speciality_number,presence: true, length: { maximum: 15}
  validates :content, presence: true

  acts_as_taggable
  acts_as_taggable_on :tags

  searchable do
    text :title, :default_boost => 2
    text :content
    text :description
    text :speciality_number
  end

  ratyrate_rateable "rating"

  paginates_per 10
end

app/controllers/conspects_controller.rb
class ConspectsController < ApplicationController
  before_action :set_conspect, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :conspect_modify_permission, only: [:destroy, :update, :edit]

  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  # GET /conspects
  # GET /conspects.json
  def index
    @search = Conspect.solr_search do
      fulltext params[:search]
      paginate page: params[:page], per_page: 10
    end
    if @search.results.empty?
      flash[:error] = 'Nothing found'
      @conspects = Conspect.all.page params[:page]
    else
      @conspects = @search.results
    end
    if params[:tag]
      @conspects = Conspect.tagged_with(params[:tag]).page params[:page]
    end
  end

  # GET /conspects/1
  # GET /conspects/1.json
  def show
  end

  # GET /conspects/new
  def new
    @conspect = Conspect.new
  end

  # GET /conspects/1/edit
  def edit
  end

  # POST /conspects
  # POST /conspects.json
  def create
    @conspect = Conspect.new(conspect_params)
    @conspect.user_id = current_user.id

    respond_to do |format|
      if @conspect.save
        format.html { redirect_to @conspect, notice: 'Conspect was successfully created.' }
        format.json { render :show, status: :created, location: @conspect }
      else
        format.html { render :new }
        format.json { render json: @conspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conspects/1
  # PATCH/PUT /conspects/1.json
  def update
    respond_to do |format|
      if @conspect.update(conspect_params)
        format.html { redirect_to @conspect, notice: 'Conspect was successfully updated.' }
        format.json { render :show, status: :ok, location: @conspect }
      else
        format.html { render :edit }
        format.json { render json: @conspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conspects/1
  # DELETE /conspects/1.json
  def destroy
    @conspect.destroy
    respond_to do |format|
      format.html { redirect_to conspects_url, notice: 'Conspect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conspect
      @conspect = Conspect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conspect_params
      params.require(:conspect).permit(:title, :description, :speciality_number, :content, :tag_list)
    end

    def conspect_modify_permission
      unless @conspect.user_id == current_user.id || current_user.admin?
        flash[:notice] = 'Only admin or owner of conspect can modify it'
        redirect_to root_path
      end
    end

end

app/helpers/conspects_helper.rb
module ConspectsHelper
end

app/views/conspects/_form.html.erb
<%= form_with(model: conspect, local: true) do |form| %>
  <% if conspect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conspect.errors.count, "error") %> prohibited this conspect from being saved:</h2>

      <ul>
      <% conspect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>

    <div class="form-group mt-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :tag_list, 'Tags' %>
      <%= form.autocomplete_field :tag_list, autocomplete_tag_name_conspects_path, :"data-delimiter" => ', ', class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :speciality_number %>
      <%= form.number_field :speciality_number, class: "form-control" %>
    </div>

    <br>

    <div class="form-group">
      <%= form.hidden_field :content, id: :conspect_body %>
      <trix-editor input="conspect_body"> </trix-editor>
    </div>

    <div class="actions d-flex justify-content-center mb-2">
      <%= form.submit class: "btn btn-primary" %>
    </div>

  </form>

<% end %>

app/views/conspects/edit.html.erb
<h3 class="text-center mt-3">Edit Conspect</h3>

<%= render 'form', conspect: @conspect %>

<div class="d-flex justify-content-center mb-2">
  <%= link_to 'Show', @conspect %> |
  <%= link_to 'Back', @conspect %>
</div>

app/views/conspects/index.html.erb
<div class="d-flex justify-content-center mt-3">
  <div id="tag_cloud">
    <% tag_cloud Conspect.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>

<br>

<table class="mb-2">
  <thead>
    <tr>
      <th class="text-center">Title</th>
      <th class="text-center">Description</th>
      <th class="text-center">Tags</th>
      <th class="text-center">Speciality number</th>
      <th class="text-center">Rating</th>
      <th class="text-center">User</th>
      <th class="text-center">Created at:</th>
      <th colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @conspects.each do |conspect| %>
      <tr>
        <td><%= conspect.title %></td>
        <td><%= conspect.description %></td>
        <td><%= raw conspect.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %></td>
        <td class="text-center"><%= conspect.speciality_number %></td>
        <td><%= rating_for conspect, "rating", disable_after_rate: true, cancel: false %></td>
        <td><%= conspect.user.email %></td>
        <td><%= conspect.created_at.strftime("%d-%m-%Y | %H-%M-%S") %></td>
        <td><%= link_to 'Show', conspect %></td>
        <td><%= link_to 'Edit', edit_conspect_path(conspect) %></td>
        <td><%= link_to 'Destroy', conspect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center mb-2">
<%= link_to 'Create Conspect', new_conspect_path%>
</div>

<div class="d-flex justify-content-center">
  <%= paginate @conspects %>
</div>

app/views/conspects/new.html.erb
<h3 class="text-center mt-3">Create new conspect</h3>

<%= render 'form', conspect: @conspect %>

<%= link_to 'Back', conspects_path, class: "d-flex justify-content-center" %>

app/views/conspects/show.html.erb
<h3 class="text-center mt-3">Conspect info:</h3>

  <strong>Author:</strong>
  <h6><%= @conspect.user.email %></h6>

  <strong>Title:</strong>
  <h6><%= @conspect.title %></h6>

  <strong>Description:</strong>
  <h6><%= @conspect.description %></h6>

  <strong>Tags:</strong>
  <h6><%= @conspect.tag_list %></h6>

  <strong>Rating:</strong>
  <%= rating_for @conspect, "rating", disable_after_rate: true, cancel: false %>

  <strong>Created at:</strong>
  <h6><%= @conspect.created_at.strftime("%d-%m-%Y | %H-%M-%S") %></h6>

  <strong>Speciality number:</strong>
  <h6><%= @conspect.speciality_number %></h6>

  <hr>
  <h6 class="text-center">Conspect:</h6>
  <%= sanitize @conspect.content %>
  <hr>

<div class="d-flex justify-content-center mb-2">
  <%= link_to 'Edit ', edit_conspect_path(@conspect) %> |
  <%= link_to ' Back', conspects_path %>
</div>

<hr>

<h3 class="text-center">Comments: <%= @conspect.comments.count %></h3>

<%= render 'comments/comment' %>

<h5 class="text-center">Add comment:</h5>

<%= render 'comments/form' %>