config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'conspects/tags/:tag', to: 'conspects#index', as: :tag
  root 'conspects#index'
  resources :photos
  resources :conspects do
    get :autocomplete_tag_name, :on => :collection
    resources :comments do
      member do
        put 'like', to: 'comments#upvote'
      end
    end
  end

  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  UNRANSACKABLE_ATTRIBUTES = %w(id created_at)
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :conspects, dependent: :destroy

  acts_as_voter

  ratyrate_rater

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

  paginates_per 10
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :user_admin, only: [:show, :destroy, :update, :edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @conspects = @user.conspects.all
    @search = @conspects.ransack(params[:q])
    @search.build_condition
    @conspects = @search.result.page(params[:page]).per(10)
  end

  # GET /users/new
  def new
    # @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { respond_with_bip(@user) }
      else
        format.html { render :edit }
        format.json { respond_with_bip(@user) }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :admin, :blocked, :name, :gender, :date_of_birth)
    end

    def user_admin
      unless current_user.try(:admin?) || current_user == @user
        flash[:notice] = 'Only admin can modify other user account'
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_role
    if current_user.admin?
      "Logged as: #{current_user.email} (Admin)"
    else
      "Logged as: #{current_user.email}"
    end
  end

end

app/views/users/_condition_fields.erb
<div>
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select %>
  <% end %>
  <%= f.predicate_select only: %i(cont lt gt null) %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <% if current_user.admin? %>

    <div class="form-group">
      <%= form.label :admin %>
      <%= form.check_box :admin %>
    </div>

    <div class="form-group">
      <%= form.label :blocked %>
      <%= form.check_box :blocked %>
    </div>

    <% end %>

    <div class="d-flex justify-content-center">
      <div class="form-group">
        <div class="actions">
          <%= form.submit class: "btn btn-primary" %>
        </div>
      </div>
    </div>

  </form>
<% end %>

app/views/users/edit.html.erb
<h3 class="text-center mt-3 mb-3">Editing User</h3>

<%= render 'form', user: @user %>

<div class="d-flex justify-content-center">
<%= link_to 'Show', @user %>
</div>

app/views/users/index.html.erb
<h3 class="text-center mt-3 mb-3">Users list</h3>

<table class="table">
  <thead>
    <tr>
      <th class="text-center" scope="col">Email</th>
      <th colspan="3" class="text-center" scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="text-center" scope="row"><%= user.email %></td>
        <td scope="row"><%= link_to 'Show', user %></td>
        <td scope="row"><%= link_to 'Edit', edit_user_path(user) %></td>
        <td scope="row"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="d-flex justify-content-center">
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<!--<h1>New User</h1>-->

<%#= render 'form', user: @user %>

<%#= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h3 class="text-center mb-3 mt-3">User info</h3>

<form class="mt-3">
  <div class="form-group">
    <label>Email:</label>
    <%= @user.email %>
  </div>
  <div class="form-group">
    <label>Name:</label>
    <%= best_in_place @user, :name, inner_class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Gender:</label>
    <%= best_in_place @user, :gender, :as => :select, :collection => %w(Male Female), inner_class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Birth date:</label>
    <%= best_in_place @user, :date_of_birth, :as => :date %>
  </div>

  <%= link_to 'Edit', edit_user_path(@user), class: "d-flex justify-content-center" %>

</form>

<hr>

<% if !@user.conspects.blank? %>

  <label>Filter:</label>
  <%= search_form_for @search, url: user_url do |f| %>
    <%= f.condition_fields do |c| %>
      <%= render 'condition_fields', f: c %>
    <% end %>
    <div>
      <label><%= link_to_add_fields "Add Conditions", f, :condition %></label>
      <div class="d-flex justify-content-center">
        <%= f.submit 'Filter', class: "btn btn-primary" %>
      </div>
    </div>
    <hr>
  <% end %>

  <h5 class="text-center mb-3"><%= @user.email %>'s conspects:</h5>

  <div class="container">
  <table class="mb-2">
    <thead>
    <tr>
      <th class="text-center"><%= sort_link @search, :title, 'Title' %></th>
      <th class="text-center">Description</th>
      <th class="text-center"><%= sort_link @search, :speciality_number, 'Speciality number' %></th>
      <th class="text-center">Rating</th>
      <th class="text-center"><%= sort_link @search, :created_at, 'Created at:' %></th>
      <th colspan="3" class="text-center">Actions</th>
    </tr>
    </thead>

    <tbody>
      <% @conspects.each do |conspect| %>
        <tr>
          <td><%= conspect.title %></td>
          <td><%= conspect.description %></td>
          <td><%= conspect.speciality_number %></td>
          <td><%= rating_for conspect, "rating", disable_after_rate: true, cancel: false %></td>
          <td><%= conspect.created_at.strftime("%d-%m-%Y | %H-%M-%S") %></td>
          <td><%= link_to 'Show', conspect %></td>
          <td><%= link_to 'Edit', edit_conspect_path(conspect) %></td>
          <td><%= link_to 'Destroy', conspect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center mb-2">
    <%= link_to 'Create Conspect', new_conspect_path%>
  </div>
  <% else %>
    <h5 class="text-center">No conspects are created yet. Want to make a first one?</h5>
    <div class="d-flex justify-content-center mb-2">
      <%= link_to 'New Conspect', new_conspect_path %>
    </div>
<% end %>
</div>

<div class="d-flex justify-content-center">
  <%= paginate @conspects %>
</div>